import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { spawnSync } from "child_process";

function buildOldbuddyPage() {
	const r = spawnSync(process.execPath, ["scripts/build-oldbuddy-page.mjs"], {
		stdio: "inherit",
		cwd: process.cwd(),
	});
	if (r.status !== 0) {
		throw new Error("build-oldbuddy-page failed");
	}
}

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

buildOldbuddyPage();

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
